import React from 'react';
import { motion } from 'framer-motion';

const fraudSections = [
  {
    title: "1. Account & Identity Verification",
    content: "To maintain an authentic ecosystem, PulseEvent employs structural verification protocols for all event organizers and donation campaign creators. Before publishing an event or launching a fundraiser, individuals or entities must verify their corporate identity, banking details, or legal status. This preventative baseline severely restricts anonymous malicious actors from operating within our platform."
  },
  {
    title: "2. Ticket Anti-Counterfeiting Framework",
    content: "Every ticket generated by PulseEvent features a unique, encrypted, dynamic barcode linked directly to the buyer's account configuration. Once a ticket is scanned at the venue check-in terminal, its digital entry state immediately shifts to expired. We strictly outlaw secondary ticket scraping or unverified transfer chains, eliminating typical duplication exploits and fake ticket schemes."
  },
  {
    title: "3. Donation & Fund Auditing Measures",
    content: "Fundraising campaigns are vulnerable to exploitation, which is why PulseEvent carefully tracks incoming streams. Donation pools are proactively monitored for suspicious accumulation velocities. To shield public donors, gathered balances may be subject to review cycles and milestone-based releases, ensuring money is systematically deployed for the exact charitable or community cause detailed in the campaign."
  },
  {
    title: "4. Transaction Velocity & Chargeback Tracking",
    content: "Collaborating with certified, global payment processors, we track card networks around the clock. Our network layer automatically flags high-frequency transaction velocities, compromised card signatures, or structural chargeback anomalies. Accounts found utilizing stolen profiles or engineering artificial purchase spikes will be systematically locked out, and any related transactions will be immediately voided."
  },
  {
    title: "5. Real-Time Project Red-Flagging",
    content: "We empower the PulseEvent community to protect itself. Attendees and donors can flag suspicious listings, misleading descriptions, or suspected fraudulent activity directly from any event or campaign page. Flagged items are instantly directed to our trust and safety group for rapid evaluation, which may lead to temporary suspension while we request further proof of execution from the creator."
  },
  {
    title: "6. Legal Escalation & Penalties",
    content: "PulseEvent maintains zero tolerance for criminal exploitation. Any user attempting to construct deceptive fundraising campaigns, fabricate digital entry passes, or manipulate our financial layers will face permanent profile blacklisting. Furthermore, we actively archive access logs and work alongside regulatory agencies to support prosecution efforts."
  }
];

export default function FraudPrevention() {
  return (
    <div className="min-h-screen bg-white text-gray-800 py-24 px-6 relative overflow-hidden">
      
      {/* Background Ambience */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] right-[-15%] w-[600px] h-[600px] rounded-full bg-[#5a1fb5]/5 blur-[140px]" />
        <div className="absolute bottom-[-10%] left-[-15%] w-[500px] h-[500px] rounded-full bg-[#f2378f]/5 blur-[110px]" />
      </div>

      <div className="max-w-4xl mx-auto relative z-10">
        
        {/* Header Section */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-16 border-b border-gray-200 pb-10"
        >
          <h1 className="text-4xl md:text-5xl font-['Space_mono',monospace] font-bold text-gray-900 mb-4 tracking-tight">
            Fraud <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#5a1fb5] to-[#c13ac7]">Prevention</span>
          </h1>
          <p className="text-gray-600 text-lg font-medium">
            How we protect ticketing integrity, verified donation routing, and ecosystem transaction pools.
          </p>
        </motion.div>

        {/* Dynamic Fraud Prevention Content */}
        <div className="space-y-12">
          {fraudSections.map((section, index) => (
            <motion.div 
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.5, delay: index * 0.1 }}
              className="group"
            >
              <h2 className="text-2xl font-bold mb-4 text-gray-900 group-hover:text-[#5a1fb5] transition-colors duration-300">
                {section.title}
              </h2>
              <p className="text-gray-700 leading-relaxed text-base md:text-lg">
                {section.content}
              </p>
            </motion.div>
          ))}
        </div>

        {/* Trust & Safety Footer Note */}
        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.5 }}
          className="mt-20 p-6 bg-[#f7f7fa] border border-gray-200 rounded-2xl text-sm text-gray-500 text-center"
        >
          <p>
            PulseEvent is committed to maintaining a transparent, clean environment for live engagement and authentic fundraising. If you discover a security vulnerability or wish to file an accelerated investigation request, please report the case to our Trust & Safety Team.
          </p>
        </motion.div>

      </div>
    </div>
  );
}